### ISSUE TITLE
Can not find chrome binary or the version does not match

### ISSUE THREAD

**Issue by PolynomialDivision** [jitsi/jitsi-meet-torture#272]
In the Arch Linux User Repository are different google-chrome versions.

If I install normal `google-chrome` the version is not correct

> java.util.concurrent.ExecutionException: org.openqa.selenium.SessionNotCreatedException: session not created: This version of ChromeDriver only supports Chrome version 83

If I install the 83 version `google-chrome-beta` the

>java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: unknown error: cannot find Chrome binary

There is another closed issue: https://github.com/jitsi/jitsi-meet-torture/issues/210
I exchanged the [chrome path](https://github.com/jitsi/jitsi-meet-torture/blob/master/scripts/google-chrome-stable-mahimahi.sh#L31)

    CHROME=/usr/bin/google-chrome-beta

I think the binary path is fetched here:
https://github.com/jitsi/jitsi-meet-torture/blob/master/src/test/java/org/jitsi/meet/test/web/WebParticipantFactory.java#L118

Further I tried several symlinks and 

    -Dexec.args="google-chrome-beta"

Does somebody know where I should symlink(?) the chrome executable so that the WebDriverManager finds my chrome?

**Comment by PolynomialDivision** [comment]
Updating webdrivermanager to latest version and installint `google-chrome` from AUR fixed everything! :)

**Comment by KomalElevate** [comment]
apologies for trying to merge.. It was done by mistake..
