### ISSUE TITLE
test fails because language is not english.

### ISSUE THREAD

**Issue by vipcxj** [jitsi/jitsi-meet-torture#280]
It seems that the test is based on english, the element selecter is based on the language-spec selecter, so lot's of test fails because of unable to find the element.
for example `$("*[aria-label='Toggle mute audio']")` will find nothing, but `$("*[aria-label='静音 / 取消静音']")` will find the correct element on my computer.

**Comment by saghul** [comment]
Yep, that's correct. Since English is the canonical language (the others are just translations) this is by design.

**Comment by vipcxj** [comment]
We can force selenium to use English instead of the system language.

**Comment by saghul** [comment]
If you can make a PR that would be a welcome addition!
