### ISSUE TITLE
Sound is not playing, only some videos are playing

### ISSUE THREAD

**Issue by ludi81** [jitsi/jitsi-meet-torture#283]
Hi,

i use the script /scripts/malleus.sh to test my jitsi server. The sound will not be played.
I changed added the absolute path in the WebParticipantOptions.initDefaults function to:
defaults.setProperty(PROP_FAKE_AUDIO, "/home/seluser/fakeAudioStream.wav");

I added an output to see the options from the Chrome request.
The options contains: use-file-for-fake-audio-capture=/home/seluser/fakeAudioStream.wav,
The file exsits at the node.

It seams, that everything is configured correctly. But I am not able to hear the sound at an other participant.

The video file works fine when using the FourPeople_1280x720_60.y4m file, but if I test another file the videos will not be transmitted.

Can anyone give me a hint?

**Comment by damencho** [comment]
The torture audio is muted https://github.com/jitsi/jitsi-meet-torture/blob/e171ad8e9982384d086493d87409ff974ad5c021/src/test/java/org/jitsi/meet/test/web/WebParticipantFactory.java#L216

**Comment by damencho** [comment]
Use the community forum for questions before opening new issues, thanks.
