### ISSUE TITLE
Participants [Chrome] in headless mode

### ISSUE THREAD

**Issue by tusharsonawanes** [jitsi/jitsi-meet-torture#345]
Hello, 

I am following [this ](https://community.jitsi.org/t/tutorial-loadtesting-jitsi-with-malleusjitsificus-on-a-selenium-grid/33302) tutorial for setting up my testing environment. The Selenium grid machine is where I have my jdk and the selenium grid configured. All the other nodes ( Ubuntu 18.04, GUI, chrome) have joined the same successfully. ( Not using the root user )

When I configure 30 chrome instances in every node, I can successfully see them listed in my selenium grid endpoint. 

**Problem.** 

When I run the tests from the selenium node using this command

```./scripts/malleus.sh --conferences=1 --participants=90 --senders=1 --audio-senders=2 --duration=1000 --room-name-prefix=hamertesting --hub-url=http://seleniumhub:4444/wd/hub --instance-url=https://myjitsiinstallation```

I can see that only ~50-60 chrome instances join the meeting. Moreover, I see that the 50-60 pariticipants ( Chrome instances ) get opened on my Laptop. When I keep the task manager open, I see that the CPU utilization is full at 60th participant because of which java throws an exception and the further participants ( chrome instances ) cannot start.

**What is expected**

Can I have the 50-60 chrome instances running in a headless mode ? I can just go to the instance url and see all the participants listed there. ( The 50-60 chrome instances should not open on my laptop ) 

![image](https://user-images.githubusercontent.com/12230324/107138942-b70df980-693d-11eb-9d65-4c478cdf8d52.png)

**Comment by damencho** [comment]
The chrome instances should be running on the nodes, not locally on the machine where you run torture 
https://github.com/jitsi/jitsi-meet-torture/blob/c1fcdcd61549224fe3837e4130a13c4011af1165/scripts/malleus.sh#L159
That is strange

**Comment by tusharsonawanes** [comment]
Exactly. I see a lot of chrome instances in my laptop. 

Just a question : 

Is it happening because I take selenium grid shell from my laptop ?
