### ISSUE TITLE
pingInterval setting does not effect in torture

### ISSUE THREAD

**Issue by ahmetkarakaya** [jitsi/jitsi-meet-torture#359]
I have set pingInterval: -1, in config file. But Torture tool is still sending colibri ping messages by 1 second interval. Each participant sending the ping message. If there is 21 partiticipant in a room, it means 20TPS messages should be handled in browser, this causes high cpu and nw bandwidth usage

**Comment by damencho** [comment]
Please when you have questions or problems use the community forum before opening new issues, thank you.

Are you talking here about e2eping.pingInterval?

**Comment by ahmetkarakaya** [comment]
> Please when you have questions or problems use the community forum before opening new issues, thank you.
> 
> Are you talking here about e2eping.pingInterval?
