### ISSUE TITLE
Specific Room to torture

### ISSUE THREAD

**Issue by holema** [jitsi/jitsi-meet-torture#487]
Hello @all,
thanks for the great tool.
I want to test a specific room with the torture test. 
Is there a way to bypass the URL generation which sets the baseURL+prefix+integer to just the url I enterd into the command?
That would be great, because then I can anter a room URL together with the jwt token.

best regards

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Not without a code change, sorry.
