### ISSUE TITLE
Where can I find the detailed test Results

### ISSUE THREAD

**Issue by thisisnkc** [jitsi/jitsi-meet-torture#552]
I know this is very silly of me that I cannot find the test results after successful completion of the test. 

Although it displays minor details, like:
![Screenshot 2022-11-11 at 6 47 08 PM](https://user-images.githubusercontent.com/81152814/201348448-9053c0ca-5c50-4ed5-8ad2-04c4db9e43c4.png)

I want a detailed report of the test, where can I find it.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

In the target folder.

**Comment by thisisnkc** [comment]
Hey @damencho ,

I already posted the issue on the community forum and got no reply whatsoever.

please elaborate “targeted folder”.
I need the full path.

**Comment by damencho** [comment]
I haven't seen your oost there, vut maybe I have missed it.

There is a folder named target.
