### ISSUE TITLE
change browser type for malleus script

### ISSUE THREAD

**Issue by crjo** [jitsi/jitsi-meet-torture#647]
Hi,

I'm starting malleus script with this parameters : 
malleus.sh --conferences=1 --participants=1 --senders=0 --audio-senders=0 --duration=60 --hub-url=http://selenium-hub:4444/wd/hub --instance-url=https://example.com

How can i specify the type of browser to use ?
Actually it's Chrome by default, i wish it was Firefox.

Regards

**Comment by damencho** [comment]
Change the default here: https://github.com/jitsi/jitsi-meet-torture/blob/995cb677b98f2f4193a6c96680173262b5950899/src/test/java/org/jitsi/meet/test/base/ParticipantHelper.java#L153

Or if it is just for one participant then here:
https://github.com/jitsi/jitsi-meet-torture/blob/9dba8724fc5617dac2b08c46f3e5eb6c811ad954/scripts/malleus.sh#L210
You can add `-Dweb.participant1.type=firefox \`

**Comment by damencho** [comment]
When you have questions or problems use the community forum before opening new issues, thank you.
